name: Clojure CI

on:
  push:
    branches: [ development ]
  # pull_request:
  #   branches: [ development ]
  repository_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Event Information
      run: |
        echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"

    - name: pull frontend
      run: cd /srv/y-video-back-end/y-video-back-end ls
    # - uses: actions/checkout@v2
    # - name: Install dependencies
    #   run: lein deps


# dispatch response to yvideo-frontend
    # - name: Dispatch response to received from yvideo-frontend
    #   if: github.event.action == 'yvideo-frontend'
    #   run: |
    #     curl -X POST https://api.github.com/repos/youthrich40/y-video-frontend/dispatches \
    #     -H 'Accept: application/vnd.github.everest-preview+json' \
    #     -u ${{ secrets.YVIDEO_ACCESS_TOKEN }} \
    #     --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
