name: Clojure CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  repository_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Event Information
      run: |
        echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
    - name: PONG - Dispatch response to received PING
      if: github.event.action == 'ping'
      run: |
        curl -X POST https://api.github.com/repos/youthrich40/y-video-frontend/dispatches \
        -H 'Accept: application/vnd.github.everest-preview+json' \
        -u ${{ secrets.YVIDEO_ACCESS_TOKEN }} \
        --data '{"event_type": "pong", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
